
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider, Text } from "@chakra-ui/react";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Food Dashboard | Authentication',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <ChakraProvider>
                <body className={`${inter.className}`}>
                    {
                        children
                    }
                </body>
            </ChakraProvider>
        </html>
    )
}
