'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider } from "@chakra-ui/react";
import { Footer } from '@/components/Footer';
import DialogNavigation from '@/components/DialogNavigation';
import LoadingPageLayout from '@/components/LoadingPage';
import { auth } from '@/db_init';
import { onAuthStateChanged } from 'firebase/auth';
import { useRouter } from 'next/navigation';
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Food',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    
    const [isLoading, setIsLoading] = useState<boolean>(true)

    const router = useRouter()

    useEffect(() => {
        onAuthStateChanged(auth, (user) => {
            if (user == null) {
                router.replace('/auth/login', {})
            } else {
                setIsLoading(false)
            }
        })
    })


    return (
        <html lang="en">
            <body className={`${inter.className} relative`}>
            <LoadingPageLayout
                        isLoading={isLoading}
                    >
                <ChakraProvider>
                    
                    <DialogNavigation />
                    {children}
                    <Footer />
                </ChakraProvider>
                </LoadingPageLayout>
            </body>
        </html>
    )
}
