'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider } from "@chakra-ui/react";
import { Footer } from '@/components/Footer';
import DialogNavigation from '@/components/DialogNavigation';
import { useEffect, useState } from 'react';
import { User, onAuthStateChanged } from 'firebase/auth';
import { auth } from '@/db_init';
import UserContext from '@/context/userContext';


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Food',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const [user, setUser] = useState<User | null>(null)

    useEffect(
        () => {

            const unsub = () => {
                onAuthStateChanged(
                    auth,
                    (user) => {
                        setUser(user)
                    }
                )
            }
            return unsub()

        }, []
    )

    return (
        <html lang="en">
            <body className={`${inter.className} relative`}>


                <ChakraProvider>
                    <UserContext.Provider value={user}>
                        <DialogNavigation />
                        {children}
                    </UserContext.Provider>
                    <Footer />
                </ChakraProvider>

            </body>
        </html>
    )
}
