
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProvider, Text } from "@chakra-ui/react";
import Sidebar from '../components/Sidebar';
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Food Dashboard',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <ChakraProvider>
                <body className={`${inter.className}`}>

                    <div className={`relative flex`}>
                        <nav className={'hidden md:block md:w-1/5 bg-slate-100 h-screen p-3'}>
                            <Sidebar />
                        </nav>
                        <main className='w-full md:w-4/5 md:h-screen md:overflow-auto'>
                            <NextTopLoader
                                color="#2299DD"
                                initialPosition={0.08}
                                crawlSpeed={200}
                                height={3}
                                crawl={true}
                                showSpinner={false}
                                easing="ease"
                                speed={200}
                                shadow="0 0 10px #2299DD,0 0 5px #2299DD"
                            />
                            {children}
                        </main>
                    </div>
                </body>
            </ChakraProvider>
        </html>
    )
}
